version: '3'

networks:
  api-mysql-bridge:
    driver: bridge

services: 
  mysql:
    image: mysql
    restart: always
    env_file: ./.env
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init-files:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - 3306:3306
    networks:
      - api-mysql-bridge
  app:
    build: .
    image: api
    ports: 
      - 3000:3000
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - api-mysql-bridge

  